{
 "title": "Map · Driving Heatmap",
 "tags": [ "tesla" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT\n    id as __value,\n    CASE WHEN COUNT(id) OVER (PARTITION BY name) > 1 AND name IS NOT NULL THEN CONCAT(name, ' - ', RIGHT(vin, 6)) ELSE COALESCE(name, CONCAT('VIN ', vin)) end as __text \nFROM cars\nORDER BY display_priority ASC, name ASC, vin ASC;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Driving Heatmap",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude\nFROM positions\nWHERE car_id = $car_id AND $__timeFilter(date)\n  AND ideal_battery_range_km IS NOT NULL AND mod(id, 4) = 0;"
    }
   ]
  },
  {
   "title": "Positions Plotted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) AS \"Points\"\nFROM positions\nWHERE car_id = $car_id AND $__timeFilter(date)\n  AND ideal_battery_range_km IS NOT NULL AND mod(id, 4) = 0;"
    }
   ]
  },
  {
   "title": "Distance in Period ($length_unit)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT convert_km(sum(distance)::numeric, '$length_unit') AS \"Distance\"\nFROM drives\nWHERE car_id = $car_id AND $__timeFilter(start_date) AND end_date IS NOT NULL;"
    }
   ]
  }
 ]
}